version: "3"

services:
  bethehero:
    build: . ## localização do dockerfile
    container_name: bethehero_app
    depends_on:
      - db
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app/bethehero
    links:
      - db

  db:
    container_name: bethehero_database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MasterBeTheHero
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
      - "33060:33060" 
